# Generated by Django 5.0 on 2023-12-25 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(blank=True, db_index=True, default=None, max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)], verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(upload_to='static/src/')),
                ('status', models.BooleanField(default=True, verbose_name='Availability')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('status', '-price'),
            },
        ),
    ]
