# Generated by Django 5.0.3 on 2024-03-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothset',
            old_name='table_num',
            new_name='person',
        ),
    ]
