# Generated by Django 5.0.3 on 2024-04-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_rename_table_num_clothset_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежды'},
        ),
        migrations.AlterModelOptions(
            name='clothcategory',
            options={'verbose_name': 'Категория одежды', 'verbose_name_plural': 'Категории одежды'},
        ),
        migrations.AlterModelOptions(
            name='clothset',
            options={'verbose_name': 'Выдача', 'verbose_name_plural': 'Выдачи'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='patranomic',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_app.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tabel_num',
            field=models.CharField(db_index=True, max_length=24, unique=True, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Должность'),
        ),
    ]
