# Generated by Django 5.0.2 on 2024-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_remove_book_category_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое описание'),
        ),
    ]
