# Generated by Django 5.0.2 on 2024-02-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_tag_alter_book_categories_book_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
