# Generated by Django 5.0.2 on 2024-03-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='ip_address',
            new_name='ip',
        ),
    ]
