# Generated by Django 5.0.1 on 2024-01-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=300, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, unique=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-title',),
            },
        ),
    ]
