# Generated by Django 5.0.1 on 2024-01-13 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=300, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, unique=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('price', models.PositiveIntegerField(blank=True, default='', verbose_name='Price')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('category', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='django_app.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, db_index=True, default='', max_length=100, to='django_app.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('status', 'id'),
            },
        ),
    ]
